# phần này ko khai báo spring.profiles nên là "default" profile
# để ý cú pháp:  spring.cloud.config.server.native.searchlocations = /config/{application}/{profile}]
# spring-cloud-config-client sẽ gọi  Uri = /app1/default
spring:
  application:
    name: app1       # = {application}
    version: 1.0
server:
  port: 8889

myLib:
    param1: value1
    param2: value2
    comment: "dùng @ConfigurationProperties để map thông tin sau với JavaObject"
---
spring:
  profiles:         # = {profile}
    - dev           # spring-cloud-config-client sẽ gọi Uri = /app1/dev
message: version for dev

---
spring:
  profiles:         # = {profile}
    - prod          # spring-cloud-config-client sẽ gọi Uri = /app1/prod
message: version for product

