# dùng @ConfigurationProperties để map thông tin sau với JavaObject
lib1:
    param1: value1
    param2: value2
    param3: value3, value4, value5
    comment: "dùng @ConfigurationProperties để map thông tin sau với JavaObject"


